apiVersion: v1
kind: Pod
metadata:
  name: go-pod
spec:
  containers:
  - image: ipenguin/jenkins-agent-golang
    name: jnlp
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: builddir
  volumes:
  - name: builddir
    emptydir: {}

